# Generated by Django 4.0.3 on 2022-03-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachmentmodel',
            table='attachments_doc',
        ),
        migrations.AlterModelTable(
            name='firmodel',
            table='main_table',
        ),
    ]
