# Generated by Django 4.0.3 on 2022-03-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0002_alter_attachmentmodel_table_alter_firmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachmentmodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='complainant',
            table=None,
        ),
        migrations.AlterModelTable(
            name='crime',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fir',
            table=None,
        ),
        migrations.AlterModelTable(
            name='suspect',
            table=None,
        ),
    ]
