# Generated by Django 4.0.3 on 2022-03-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0003_alter_attachmentmodel_table_alter_complainant_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachmentmodel',
            table='attachments_doc',
        ),
        migrations.AlterModelTable(
            name='complainant',
            table='complainant_info',
        ),
        migrations.AlterModelTable(
            name='crime',
            table='crime_info',
        ),
        migrations.AlterModelTable(
            name='fir',
            table='fir_details',
        ),
        migrations.AlterModelTable(
            name='suspect',
            table='suspect_info',
        ),
    ]
