# Generated by Django 4.0.3 on 2022-03-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0004_alter_attachmentmodel_table_alter_complainant_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachmentmodel',
            old_name='Aaddhar_copy',
            new_name='aaddhar_copy',
        ),
        migrations.RemoveField(
            model_name='firmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='firmodel',
            name='request_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='attachmentmodel',
            table='attachment_doc',
        ),
    ]
