# Generated by Django 4.0.3 on 2022-03-24 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0005_rename_aaddhar_copy_attachmentmodel_aaddhar_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attachmentmodel',
            name='request_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FIR.firmodel'),
        ),
        migrations.AlterField(
            model_name='complainant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complainant',
            name='request_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FIR.firmodel'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crime',
            name='request_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FIR.firmodel'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fir',
            name='request_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FIR.firmodel'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='request_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FIR.firmodel'),
        ),
    ]
