# Generated by Django 4.0.3 on 2022-03-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0006_alter_attachmentmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complainant',
            table=None,
        ),
    ]
