# Generated by Django 4.0.3 on 2022-03-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0008_alter_attachmentmodel_id_alter_complainant_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachmentmodel',
            table='Attachment_Doc',
        ),
        migrations.AlterModelTable(
            name='complainant',
            table='Complainant_Info',
        ),
        migrations.AlterModelTable(
            name='crime',
            table='Crime_Info',
        ),
        migrations.AlterModelTable(
            name='fir',
            table='Fir_Details',
        ),
        migrations.AlterModelTable(
            name='firmodel',
            table='Main_Table',
        ),
        migrations.AlterModelTable(
            name='suspect',
            table='Suspect_Info',
        ),
    ]
