# Generated by Django 4.0.3 on 2022-04-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0010_alter_attachmentmodel_id_alter_complainant_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachmentmodel',
            old_name='request_no',
            new_name='request_no_id',
        ),
        migrations.RenameField(
            model_name='complainant',
            old_name='request_no',
            new_name='request_no_id',
        ),
        migrations.RenameField(
            model_name='crime',
            old_name='request_no',
            new_name='request_no_id',
        ),
        migrations.RenameField(
            model_name='fir',
            old_name='request_no',
            new_name='request_no_id',
        ),
        migrations.RenameField(
            model_name='suspect',
            old_name='request_no',
            new_name='request_no_id',
        ),
    ]
