# Generated by Django 4.0.3 on 2022-04-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0011_rename_request_no_attachmentmodel_request_no_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachmentmodel',
            old_name='request_no_id',
            new_name='request_no',
        ),
        migrations.RenameField(
            model_name='complainant',
            old_name='request_no_id',
            new_name='request_no',
        ),
        migrations.RenameField(
            model_name='crime',
            old_name='request_no_id',
            new_name='request_no',
        ),
        migrations.RenameField(
            model_name='fir',
            old_name='request_no_id',
            new_name='request_no',
        ),
        migrations.RenameField(
            model_name='suspect',
            old_name='request_no_id',
            new_name='request_no',
        ),
    ]
