# Generated by Django 4.0.3 on 2022-04-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0012_rename_request_no_id_attachmentmodel_request_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complainant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crime',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fir',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
