# Generated by Django 4.0.3 on 2022-04-01 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0014_alter_complainant_addhar_no_alter_complainant_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='doa',
        ),
        migrations.AddField(
            model_name='complainant',
            name='doa',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
