# Generated by Django 4.0.3 on 2022-04-04 18:13

import FIR.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0015_remove_crime_doa_complainant_doa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmodel',
            name='aaddhar_copy',
            field=models.ImageField(blank=True, null=True, upload_to=FIR.models.get_filename),
        ),
    ]
