# Generated by Django 4.0.3 on 2022-04-04 18:42

import FIR.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0016_alter_attachmentmodel_aaddhar_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmodel',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to=FIR.models.get_filename),
        ),
    ]
