# Generated by Django 4.0.3 on 2022-05-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0017_alter_attachmentmodel_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmodel',
            name='aaddhar_copy',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='attachmentmodel',
            name='sign',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
        migrations.AlterModelTable(
            name='attachmentmodel',
            table=None,
        ),
    ]
