# Generated by Django 4.0.3 on 2022-05-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0018_alter_attachmentmodel_aaddhar_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmodel',
            name='aaddhar_copy',
            field=models.ImageField(upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='attachmentmodel',
            name='sign',
            field=models.ImageField(upload_to='img/%y'),
        ),
        migrations.AlterModelTable(
            name='attachmentmodel',
            table='Attachment_doc',
        ),
    ]
