# Generated by Django 4.0.3 on 2022-05-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0019_alter_attachmentmodel_aaddhar_copy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentmodel',
            name='request_no',
        ),
    ]
