# Generated by Django 4.0.3 on 2022-05-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0020_remove_attachmentmodel_request_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmodel',
            name='comments',
            field=models.TextField(default=0, max_length=150),
        ),
    ]
