# Generated by Django 4.0.3 on 2022-05-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0022_police_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainant',
            name='request_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FIR.firmodel'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='request_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FIR.firmodel'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='request_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FIR.firmodel'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='request_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FIR.firmodel'),
        ),
    ]
