# Generated by Django 4.0.3 on 2022-05-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0023_alter_complainant_request_no_alter_crime_request_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainant',
            name='crime_pincode',
            field=models.IntegerField(default=400067),
            preserve_default=False,
        ),
    ]
