# Generated by Django 4.0.3 on 2022-05-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIR', '0024_complainant_crime_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmodel',
            name='police_id',
            field=models.IntegerField(default=0),
        ),
    ]
